---
title: "Untitled"
author: "Weidi Zhang"
date: "2024-10-24"
output: html_document
---

```{r setup, include=FALSE}
options(future.globals.maxSize = 16 * 1024^3)

merge_s <- readRDS("/Users/wdz/Documents/Research/Kidney_transplant/RDS/Kidney_IGF_PNF.rds")

merge_s <- merge_s %>%
    NormalizeData(verbose = FALSE)
merge_s <- subset(merge_s, subset = nFeature_RNA > 50 & nFeature_RNA < 1100)
VariableFeatures(merge_s) <- split(row.names(merge_s@meta.data), merge_s@meta.data$stim) %>% lapply(function(cells_use) {
    merge_s[,cells_use] %>%
        FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% 
        VariableFeatures()
}) %>% unlist %>% unique

merge_s <- merge_s %>% 
    ScaleData(verbose = FALSE) %>% 
    RunPCA(features = VariableFeatures(merge_s), npcs = 20, verbose = FALSE)

merge_s <- merge_s %>% 
    RunHarmony("stim", plot_convergence = TRUE, nclust = 50, max_iter = 5, early_stop = F)

merge_s <- FindNeighbors(merge_s,reduction = "harmony", dims = 1:20)

merge_s <- FindClusters(merge_s, resolution = 1.2)

merge_s <- RunUMAP(merge_s,reduction = "harmony", min.dist = 0.1, dims = 1:20)

UMAP_merge_s_1 <- DimPlot(merge_s, reduction = "umap", pt.size = 0.01, label = TRUE, raster=FALSE)
UMAP_merge_s_1
```

```{r cars}
UMAP_merge_s_1
```

```{r}
merge_s <- FindClusters(merge_s, resolution = 2.9)
```

```{r}
merge_s_clustree <- clustree(merge_s, prefix = "RNA_snn_res.")
merge_s_clustree
```

```{r pressure, echo=FALSE}
merge_s_markers <- FindAllMarkers(merge_s, only.pos = TRUE)
merge_s_markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1)
```

```{r pressure, echo=FALSE}
merge_sc40 <- readRDS("/Users/wanglab/Downloads/Kidney_merge_c40.rds")
```

```{r}
# Filter markers for cluster 0
library(dplyr)
library(Seurat)
cluster0.markers <- FindMarkers(merge_sc40, ident.1 = 0) %>%
  dplyr::filter(avg_log2FC > 1)
# Save the cluster 0 markers to a file
saveRDS(cluster0.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster0.rds")
```

```{r}

# Cluster 26
cluster26.markers <- FindMarkers(merge_sc40, ident.1 = 26) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster26.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster26.rds")

# Cluster 25
cluster25.markers <- FindMarkers(merge_sc40, ident.1 = 25) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster25.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster25.rds")

# Cluster 24
cluster24.markers <- FindMarkers(merge_sc40, ident.1 = 24) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster24.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster24.rds")

# Cluster 23
cluster23.markers <- FindMarkers(merge_sc40, ident.1 = 23) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster23.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster23.rds")

# Cluster 22
cluster22.markers <- FindMarkers(merge_sc40, ident.1 = 22) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster22.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster22.rds")

# Cluster 21
cluster21.markers <- FindMarkers(merge_sc40, ident.1 = 21) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster21.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster21.rds")

# Cluster 20
cluster20.markers <- FindMarkers(merge_sc40, ident.1 = 20) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster20.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster20.rds")

# Cluster 19
cluster19.markers <- FindMarkers(merge_sc40, ident.1 = 19) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster19.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster19.rds")

# Cluster 18
cluster18.markers <- FindMarkers(merge_sc40, ident.1 = 18) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster18.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster18.rds")

# Cluster 17
cluster17.markers <- FindMarkers(merge_sc40, ident.1 = 17) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster17.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster17.rds")

# Cluster 16
cluster16.markers <- FindMarkers(merge_sc40, ident.1 = 16) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster16.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster16.rds")

# Cluster 15
cluster15.markers <- FindMarkers(merge_sc40, ident.1 = 15) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster15.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster15.rds")

# Cluster 14
cluster14.markers <- FindMarkers(merge_sc40, ident.1 = 14) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster14.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster14.rds")

# Cluster 13
cluster13.markers <- FindMarkers(merge_sc40, ident.1 = 13) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster13.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster13.rds")

# Cluster 12
cluster12.markers <- FindMarkers(merge_sc40, ident.1 = 12) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster12.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster12.rds")

# Cluster 11
cluster11.markers <- FindMarkers(merge_sc40, ident.1 = 11) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster11.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster11.rds")

# Cluster 10
cluster10.markers <- FindMarkers(merge_sc40, ident.1 = 10) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster10.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster10.rds")

# Cluster 9
cluster9.markers <- FindMarkers(merge_sc40, ident.1 = 9) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster9.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster9.rds")

# Cluster 8
cluster8.markers <- FindMarkers(merge_sc40, ident.1 = 8) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster8.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster8.rds")

# Cluster 7
cluster7.markers <- FindMarkers(merge_sc40, ident.1 = 7) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster7.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster7.rds")

# Cluster 6
cluster6.markers <- FindMarkers(merge_sc40, ident.1 = 6) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster6.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster6.rds")

# Cluster 5
cluster5.markers <- FindMarkers(merge_sc40, ident.1 = 5) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster5.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster5.rds")

# Cluster 4
cluster4.markers <- FindMarkers(merge_sc40, ident.1 = 4) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster4.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster4.rds")

# Cluster 3
cluster3.markers <- FindMarkers(merge_sc40, ident.1 = 3) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster3.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster3.rds")

# Cluster 2
cluster2.markers <- FindMarkers(merge_sc40, ident.1 = 2) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster2.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster2.rds")

# Cluster 1
cluster1.markers <- FindMarkers(merge_sc40, ident.1 = 1) %>% dplyr::filter(avg_log2FC > 1)
saveRDS(cluster1.markers, file = "/Users/wanglab/Documents/cluster0_markers_cluster1.rds")
```






```{r}
merge_s_markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 50) %>%
    ungroup() -> top50
unsupheatmap <- DoHeatmap(merge_s, features = top50$gene) + NoLegend()
```


```{r}
top50_gene_list <- as.data.frame(top50)
write.csv(top50_gene_list,"/Users/wanglab/Downloads/kidney_transplant/RDS/kidney_top50_marker_gene_list.csv")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
